---
title: "Makeover Monday: Week 41 (2020)"
---

# Setup

```{r setup, include=TRUE}
library(tidyverse)
library(janitor)
library(magrittr)
library(viridis)
library(countrycode)
library(extrafont)
library(scales)
library(patchwork)
library(jkmisc)
library(glue)
library(ggalt)

#library(worldtilegrid)
#devtools::install_github("hrbrmstr/worldtilegrid")
library(httr)
library(readxl)
#library(zoo)
#library(lubridate)
#library(RColorBrewer)
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  plot.title = element_text(family="Palatino Linotype", color="black", face="bold", size=24, hjust=0), 
  plot.subtitle = element_text(family="Palatino Linotype", color="black", size=12, hjust=0), 
  axis.title = element_text(family="Palatino Linotype", color="black", size=12), 
  axis.text = element_text(family="Palatino Linotype", color="black", size=18), 
  axis.ticks = element_blank(), 
  plot.caption = element_text(family="Palatino Linotype", color="black", size=12), 
  plot.background = element_blank(),
  panel.background =  element_blank(), 
  legend.background = element_blank(), 
  panel.grid.major = element_line(colour = "grey90", size = 0.5),
  panel.grid.minor = element_line(colour = "grey93", size = 0.5),
  panel.border = element_blank(), 
  #panel.border = element_rect(colour = "black", size = 0.5, fill=NA, linetype = 1),
  legend.title=element_blank(), 
  legend.text = element_text(family="Palatino Linotype", color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(family="Palatino Linotype", color="black", size=14))
```

```{r read_data, include=TRUE}
GET("https://query.data.world/s/vihrcc3hjn3umv2dy67iu2zxuyf2en", write_disk(tf <- tempfile(fileext = ".xlsx")))
df <- read_excel(tf) %>% 
  clean_names()
```


```{r financial_sectors, include=TRUE}
financial_sector <- c('Financial services - other', 
                      'Financial services - insurance',
                      'Financial services - banking')

industry_cols <- c('Financial' = 'darkorange2',
                   'Other' = 'gray80')
```

```{r mutate_df, include=TRUE}
df <- df %>% 
  mutate(financial_sector = 
           ifelse(industry_sector %in% financial_sector,
                  'Financial', 'Other')) %>% 
  mutate(industry_sector_2 = ifelse(financial_sector == 'Financial', industry_sector, 'Other'))
```

```{r industry_map, include=TRUE}
industry_map <- df %>% 
  select(financial_sector, industry_sector_2)
```

```{r glimpse, include=TRUE}
df %>% 
  glimpse()
```

```{r summary, include=TRUE}
df %>% 
  summary()
```

# Visualizations  

```{r fig.height=6.2}
df %>% 
  ggplot(.,
         aes(x=respondents_percent / 100,
               y=reorder(industry_sector, respondents_percent))) + 
  geom_col(aes(fill=financial_sector)) + 
  geom_text(aes(x=respondents_percent / 100 + .01,
                label=paste(respondents_percent, '%', sep="")),
            family='Palatino Linotype', fontface='bold') + 
  scale_x_continuous(limits = c(0, .15),
                     labels = percent) + 
  scale_fill_manual(values = industry_cols) + 
  my.theme + 
  theme(legend.position = 'none',
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=14), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
  plot_annotation(theme = theme_jk(markdown = TRUE),
                  title = "")
```

```{r fig.height=6.2}
df %>% 
  group_by(industry_sector_2) %>% 
  summarise(respondents_percent = sum(respondents_percent, na.rm=TRUE)) %>% 
  mutate(financial_sector = 
           ifelse(industry_sector_2 %in% financial_sector,
                  'Financial', 'Other'),
         industry = 'Industry') %>% 
  ggplot(.,
         aes(x=respondents_percent,
             y=industry)) + 
  geom_bar(aes(fill=financial_sector), 
           color='black',
           position = 'stack', stat = 'identity') + 
  #ggrepel::geom_text_repel(aes(label=industry_sector_2),
   #                        force=20) + 
  scale_fill_manual(values = c('Financial' = 'darkorange2',
                               'Other' = 'white')) + 
  coord_polar() + 
  my.theme + 
  theme(legend.position = 'none')
```


```{r fig.height=6.2}
df %>% 
  filter(financial_sector == 'Financial') %>% 
  ggplot(.) + 
  geom_bar(aes(x=respondents_percent /100, 
               y=reorder(industry_sector, respondents_percent),
               fill=financial_sector),
           #position = 'stack', 
           stat='identity') + 
  scale_fill_manual(values = industry_cols) + 
  scale_x_continuous(labels = percent,
                     limits = c(0, 1)) + 
  coord_polar() + 
  my.theme + 
  theme(legend.position = 'none')
```

# Saving graphics  

```{r save_graphics, include=TRUE}
ggsave("graphics/.png", ,
       width = 10, height = 8, dpi = 300)
```
