---
title: "Makeover Monday: Week 42 (2020)"
---

# Setup

```{r setup, include=TRUE}
library(tidyverse)
library(janitor)
library(magrittr)
library(viridis)
library(countrycode)
library(extrafont)
library(scales)
library(patchwork)
library(jkmisc)
library(glue)
library(ggalt)

#library(worldtilegrid)
#devtools::install_github("hrbrmstr/worldtilegrid")
#library(httr)
#library(readxl)
#library(zoo)
#library(lubridate)
#library(RColorBrewer)
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  plot.title = element_text(family="Centaur", color="black", face="bold", size=24, hjust=0), 
  plot.subtitle = element_text(family="Centaur", color="black", size=12, hjust=0), 
  axis.title = element_text(family="Centaur", color="black", size=12), 
  axis.text = element_text(family="Centaur", color="black", size=18), 
  axis.ticks.y = element_blank(), 
  plot.caption = element_text(family="Centaur", color="black", size=12), 
  plot.background = element_blank(),
  panel.background =  element_blank(), 
  legend.background = element_blank(), 
  panel.grid.major = element_line(colour = "grey90", size = 0.5),
  panel.grid.minor = element_line(colour = "grey93", size = 0.5),
  panel.border = element_blank(), 
  #panel.border = element_rect(colour = "black", size = 0.5, fill=NA, linetype = 1),
  legend.title=element_blank(), 
  legend.text = element_text(family="Centaur", color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(family="Centaur", color="black", size=14))
```

```{r read_data, include=TRUE}
df <- read.csv("https://query.data.world/s/zjsukkushtm4dh4cv4qxsg7xc3xjvy", header=TRUE, stringsAsFactors=FALSE) %>% 
  clean_names() %>% 
  select(-c(flag_codes, frequency)) %>%  
  mutate(decade = time - (time %% 10))
```

```{r countryname, include=TRUE}
(countryname <- countrycode::codelist %>% 
  select(i_location = iso3c, country = country.name.en))
```

```{r join_country, include=TRUE}
df <- df %>% 
  left_join(x=.,
            y=countryname,
            by='i_location')
```


```{r glimpse, include=TRUE}
df %>% 
  glimpse()
```

```{r summary, include=TRUE}
df %>% 
  summary()
```

# Visualizations  

## Lollipop plot  

```{r fig.height=12, fig.width=8}
df_max_year <- df %>% 
  filter(measure == 'USD_CAP',
         subject == 'OOPEXP') %>% 
  group_by(country, decade) %>% 
  #mutate(most_recent_by_decade = max(time),
   #      earliest_by_decade = min(time)) %>% 
  slice_max(time, order_by = time) %>% 
  filter(decade == 2010)

df_min_year <- df %>% 
  filter(measure == 'USD_CAP',
         subject == 'OOPEXP') %>% 
  group_by(country, decade) %>% 
  #mutate(most_recent_by_decade = max(time),
   #      earliest_by_decade = min(time)) %>% 
  slice_min(time, order_by = time) %>% 
  filter(decade == 2000)

df_max_year %>% 
  bind_rows(df_min_year) %>% 
  ungroup() %>% 
  arrange(country, time) %>% 
  select(-time) %>% 
  spread(decade, value) %>% 
  mutate(diff = `2010` - `2000`) %>% 
  arrange(-diff) %>% 
  ggplot(.) + 
  geom_dumbbell(aes(x=`2000`,
                    xend=`2010`,
                    y=reorder(country, diff),
                    colour_x = `2000`,
                    colour_xend = `2010`),
                size_x = 6, size_xend = 6) + 
  my.theme + 
  theme(axis.text = element_text(size=20))

?geom_dumbbell()
```

# Most recent 

```{r}
df %>% 
  filter(i_location == 'USA',
         subject == 'OOPEXP',
         time == 2018)
```


```{r healthexp_bar_viz, include=TRUE, fig.height=6.2}
(healthexp_bar_viz <- df %>% 
  filter(!is.na(country)) %>% 
  group_by(country, subject) %>% 
  slice_max(time) %>% 
  filter(measure == 'USD_CAP') %>% 
  ggplot(.) + 
  geom_bar(data=. %>% filter(subject == 'TOT'),
           aes(x=reorder(country, value),
               y=value),
           alpha=.6, 
           stat = 'identity') + 
  geom_point(data=. %>% filter(subject != 'TOT'),
             aes(x=reorder(country, value),
                 y=value,
                 shape=subject,
                 color=subject,
                 alpha=subject),
             size=2) + 
  scale_y_continuous(labels = dollar) + 
  labs(x='',
       y='GDP per capita (US$)\n') + 
  scale_shape_manual(values = c('COMPULSORY' = 17,
                                'OOPEXP' = 18,
                                'VOLUNTARY' = 19),
                     labels = c('Government/Compulsory', 'Out of Pocket', 'Voluntary Contributions')) + 
  scale_color_manual(values = c('COMPULSORY' = 'black',
                                'OOPEXP' = 'springgreen4',
                                'VOLUNTARY' = 'black'),
                     labels = c('Government/Compulsory', 'Out of Pocket', 'Voluntary Contributions')) + 
  scale_alpha_manual(values = c('COMPULSORY' = .25,
                                'OOPEXP' = 1,
                                'VOLUNTARY' = .25),
                     labels = c('Government/Compulsory', 'Out of Pocket', 'Voluntary Contributions')) + 
  my.theme + 
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_text(angle=90, size=12, hjust = 1, vjust = .25),
        axis.ticks = element_blank()) + 
  plot_annotation(theme=theme_jk(markdown = TRUE,
                                 plot_title_family = 'Centaur',
                                 subtitle_family = 'Centaur',
                                 caption_family = 'Centaur'),
                  title=glue('Assessing ', 
                             {highlight_text("out-of-pocket", "springgreen4", "b", 24)}, 
                             ' expenditures on healthcare around the world'),
                  subtitle='Bar size indicates average total per capita expenditures on healthcare', 
                  caption='Makeover Monday Week 42 (2020)<br>**Source**: OECD'))
```



# Saving graphics  

```{r save_graphics, include=TRUE}
ggsave("graphics/healthexp_bar_viz.png", healthexp_bar_viz,
       width = 12, height = 8, dpi = 300)
```
